### ISSUE TITLE
Add completion tracking - "Must view to complete"

### ISSUE THREAD

**Issue by mjsamberg** [TheFridayInstitute/moodle_mod_videoresource#11]

**Comment by mjsamberg** [comment]
Implemented. Assigning to @maday4 for testing.

**Comment by maday4** [comment]
As far as I can tell, this is working. You can now set completion tracking for Resource Library page types: "Show activity as complete when conditions are met", the condition being "Student must view activity to complete it". And you can choose existing Resource Library pages from the Activity Completion dropdown menu when setting access restrictions (for page and sections). Are there any other aspects that need to be tested?
